# -*- coding: utf-8 -*-
"""Quizzes por SEMANA (3 questões) — checkpoints do AulaViva e quizzes do QuizWeb LP2."""

Q = {
1: [
 ("Os três pilares da programação estruturada são:",
  ["entrada, processamento e saída", "sequência, seleção e repetição", "variáveis, tipos e funções", "telas, relatórios e bancos"],
  1, "Sequência executa em ordem; seleção decide (If/Select); repetição repete (For/Do)."),
 ("No VB6, quem RETORNA valor é:",
  ["a Sub", "a Function", "o Module", "o Label"],
  1, "Function devolve resultado; Sub executa ações."),
 ("O padrão de pastas do curso é:",
  ["tudo na área de trabalho", "LP2\\S01..S24 + PROJETO, sem acentos", "uma pasta por arquivo", "pastas com espaços"],
  1, "Caminhos simples evitam bugs no VB6 e facilitam backup."),
],
2: [
 ("SGBD é o software que:",
  ["compila o VB6", "armazena, organiza e controla o acesso aos dados", "desenha telas", "imprime cupons"],
  1, "Exemplos: MySQL, PostgreSQL, SQL Server, Access."),
 ("Para listar os bancos do servidor MySQL usamos:",
  ["SHOW DATABASES;", "LIST BANKS;", "SELECT * FROM bancos;", "DIR /B;"],
  0, "Comando de administração do cliente MySQL."),
 ("O comando que cria um banco novo é:",
  ["NEW DATABASE escola;", "CREATE DATABASE escola;", "MAKE escola;", "INSERT DATABASE escola;"],
  1, "DDL: CREATE DATABASE nome;"),
],
3: [
 ("Na string de conexão, Server indica:",
  ["o banco ativo", "o endereço do servidor (ex.: localhost)", "o driver", "a senha"],
  1, "Server = onde o SGBD está; Database = qual banco."),
 ("On Error GoTo Falha + Err.Description servem para:",
  ["ignorar erros de sintaxe", "tratar falhas em tempo de execução com mensagem útil", "reiniciar o MySQL", "compilar sem erros"],
  1, "Desvia para o rótulo e detalha o erro ocorrido."),
 ("Ao terminar de usar o banco, o programa deve:",
  ["deixar cn aberto", "chamar cn.Close", "desinstalar o driver", "reiniciar a IDE"],
  1, "Conexão aberta consome recurso do servidor."),
],
4: [
 ("CREATE TABLE pertence à família:",
  ["DML", "DDL", "DCL", "TCL"],
  1, "DDL define estrutura; DML manipula dados."),
 ("PRIMARY KEY AUTO_INCREMENT garante:",
  ["id único gerado pelo servidor", "nome sem repetição", "ordenação automática", "backup automático"],
  0, "Chave primária única, não nula, numerada automaticamente."),
 ("O SELECT mínimo para ver nome e nota é:",
  ["SELECT nome, nota FROM alunos;", "GET nome nota DE alunos;", "SHOW nome nota;", "PRINT nome, nota;"],
  0, "SELECT colunas FROM tabela;"),
],
5: [
 ("UPDATE sem WHERE:",
  ["altera só a primeira linha", "altera TODAS as linhas", "dá erro", "não faz nada"],
  1, "Por isso: SELECT de conferência com o mesmo WHERE antes."),
 ("No VB6, enviamos SQL ao servidor com:",
  ["cn.Execute", "Printer.Print", "MsgBox", "FreeFile"],
  0, "Connection.Execute; consultas retornam Recordset."),
 ("Textos em SQL usam:",
  ["aspas duplas", "aspas simples", "crases", "parênteses"],
  1, "'Ana Silva' — aspas simples; aspas duplas são do VB6."),
],
6: [
 ("Para nomes que começam com 'A':",
  ["WHERE nome = 'A'", "WHERE nome LIKE 'A%'", "WHERE nome STARTS 'A'", "WHERE LEFT nome A"],
  1, "LIKE com curinga %."),
 ("COUNT(*) com GROUP BY curso retorna:",
  ["total geral", "quantidade por curso", "só o número de cursos", "média por curso"],
  1, "Agregação calculada dentro de cada grupo."),
 ("ORDER BY nota DESC lista:",
  ["crescente", "decrescente (maiores primeiro)", "por inserção", "aleatório"],
  1, "DESC = decrescente."),
],
7: [
 ("Menu com opções fixas 1/2/3 fica mais legível com:",
  ["If aninhados", "Select Case", "Do Until", "While...Wend"],
  1, "Select Case compara um valor com casos fixos."),
 ("Do While testa a condição:",
  ["depois do bloco", "antes de cada volta", "só no final", "nunca"],
  1, "Pode executar zero vezes se começar falsa."),
 ("Sentinela é:",
  ["um erro de disco", "valor combinado que encerra a leitura (ex.: -1)", "uma Function", "um tipo de Print"],
  1, "Padrão de leitura até sentinela."),
],
8: [
 ("Dim notas(1 To 10) As Single cria:",
  ["10 variáveis soltas", "vetor com posições 1 a 10", "matriz 10×10", "registro com 10 campos"],
  1, "Array unidimensional com índices explícitos."),
 ("Para percorrer o vetor, o acesso usa:",
  ["índice fixo notas(1)", "a variável do laço notas(i)", "sempre notas(0)", "InputBox"],
  1, "Índice variável permite o percurso."),
 ("Maior/menor devem ser inicializados com:",
  ["0", "10", "o primeiro elemento", "-1"],
  2, "Garante corretude para qualquer faixa de valores."),
],
9: [
 ("Na varredura de matriz, o laço externo percorre:",
  ["colunas", "linhas", "diagonais", "índices aleatórios"],
  1, "Externo = linhas (i); interno = colunas (j)."),
 ("'Subscript out of range' indica:",
  ["índice fora dos limites declarados", "variável não declarada", "divisão por zero", "arquivo fechado"],
  0, "Ex.: m(4,1) em matriz 3×4."),
 ("Para somar POR LINHA, o acumulador deve zerar:",
  ["antes dos dois laços", "dentro do laço de linhas, antes do de colunas", "depois de tudo", "no módulo"],
  1, "Um acumulador por grupo de soma."),
],
10: [
 ("Public Type Aluno ... End Type define:",
  ["um formulário", "um registro (tipo estruturado)", "um banco", "uma consulta"],
  1, "Campos de tipos diferentes sob um nome."),
 ("O acesso à nota do i-ésimo aluno é:",
  ["turma.nota(i)", "turma(i).nota", "nota(turma,i)", "turma[i].nota()"],
  1, "Índice do vetor, ponto, campo."),
 ("Um vetor de registros equivale a:",
  ["uma coluna", "uma tabela em memória", "um índice", "um backup"],
  1, "Cada registro = linha; o vetor = conjunto de linhas."),
],
11: [
 ("Mid$(\"LINGUAGEM\", 3, 4) retorna:",
  ["LING", "NGUA", "GUAG", "AGEM"],
  1, "Posição 3, quatro caracteres: N G U A."),
 ("InStr retorna 0 quando:",
  ["acha no início", "não encontra o trecho", "texto vazio", "texto numérico"],
  1, "0 = não achou; >0 = posição inicial."),
 ("Para tirar espaços das pontas:",
  ["Trim$", "Mid$", "Left$", "UCase$"],
  0, "Trim$ corta esquerda e direita."),
],
12: [
 ("O retorno de uma Function é atribuído:",
  ["à palavra Return", "ao próprio nome da Function", "a uma global", "ao ByRef"],
  1, "Media = (n1+n2)/2."),
 ("ByVal significa:",
  ["cópia local (original protegido)", "a própria variável do chamador", "parâmetro opcional", "retorno duplo"],
  0, "Declare ByVal por segurança (padrão VB6 é ByRef)."),
 ("Function pura, no padrão do curso:",
  ["usa MsgBox", "só recebe parâmetros e retorna", "imprime com Print", "grava arquivo"],
  1, "I/O fica com quem chama."),
],
13: [
 ("Para acrescentar sem apagar, abre-se com:",
  ["For Output", "For Append", "For Input", "For Random"],
  1, "Append posiciona no fim do arquivo."),
 ("EOF(n) é True quando:",
  ["abriu o arquivo", "chegou ao fim da leitura", "deu erro de disco", "arquivo vazio"],
  1, "Condição de parada do Do While."),
 ("FreeFile devolve:",
  ["número de arquivo livre", "memória livre", "tamanho do arquivo", "data de criação"],
  0, "Evita conflito de #n entre arquivos abertos."),
],
14: [
 ("Split(linha, \";\") devolve:",
  ["texto único", "vetor de campos", "só o 1º campo", "um Type"],
  1, "partes(0), partes(1)..."),
 ("Antes de abrir para leitura, verificar existência com:",
  ["Dir(caminho) <> \"\"", "EOF(caminho)", "Len(caminho)", "FreeFile"],
  0, "Evita erro de arquivo inexistente."),
 ("Exportar com Format(nota, \"0.0\") garante:",
  ["número padronizado no arquivo", "criptografia", "compressão", "ordenação"],
  0, "Round-trip íntegro entre exportar e importar."),
],
15: [
 ("Sem rs.MoveNext no Do While Not rs.EOF:",
  ["pula linhas", "laço infinito", "fecha o rs", "erro de sintaxe"],
  1, "O ponteiro não avança."),
 ("rs!nota lê:",
  ["o nome da coluna", "o valor do campo na linha atual", "todas as linhas", "o total"],
  1, "Campo da linha corrente do Recordset."),
 ("Aspas simples dentro de texto que vira SQL são escapadas:",
  ["duplicando ('')", "removendo", "trocando por \"", "com \\ "],
  0, "'' representa aspa literal no SQL."),
],
16: [
 ("Validar no cliente antes do SQL serve para:",
  ["acelerar o servidor", "evitar comandos inválidos/perigosos", "substituir On Error", "economizar RAM"],
  1, "Defesa em camadas."),
 ("Exclusões devem ser confirmadas com:",
  ["MsgBox vbYesNo", "Print", "InputBox vazio", "Label"],
  0, "Confirmação explícita antes do DELETE."),
 ("Após incluir/alterar/excluir, a ListBox deve:",
  ["ser limpa e esquecida", "ser atualizada (refresh)", "virar arquivo", "fechar o form"],
  1, "Refresh mantém a tela coerente com o banco."),
],
17: [
 ("O comando de backup do MySQL é:",
  ["mysql --copy", "mysqldump banco > arq.sql", "BACKUP TABLE", "cn.Backup"],
  1, "Gera script .sql com estrutura + dados."),
 ("Nomes de backup devem ter:",
  ["data (banco_YYYY-MM-DD)", "só o nome do banco", "senha embutida", "extensão .exe"],
  0, "Ordena sozinho e identifica a geração."),
 ("Manter gerações (avô-pai-filho) protege contra:",
  ["falta de espaço", "cópias corrompidas/desastres tardios", "senhas fracas", "vírus"],
  1, "Se a última cópia falha, a anterior salva."),
],
18: [
 ("Para restaurar usa-se:",
  ["mysqldump < arq", "mysql banco < arq.sql", "RESTORE arq", "cn.Restore"],
  1, "O cliente mysql executa o script no banco."),
 ("Restaurar primeiro em banco de teste:",
  ["treina SQL", "não arrisca a produção na validação", "acelera o dump", "economiza disco"],
  1, "Valida arquivo e procedimento com segurança."),
 ("Validação pós-restauro inclui:",
  ["SHOW TABLES + COUNT(*) + amostras", "só tamanho do arquivo", "reiniciar o serviço", "abrir no Notepad"],
  0, "Conferência estrutural e de conteúdo."),
],
19: [
 ("Alinhamento de colunas em relatório de texto:",
  ["Space apenas", "Tab(n) e String(n,\"-\")", "MsgBox", "Printer.Page"],
  1, "Tab posiciona; String separa blocos."),
 ("Sem Printer.EndDoc:",
  ["imprime na hora", "o job fica retido", "cancela", "imprime em dobro"],
  1, "EndDoc fecha e despacha o documento."),
 ("Fonte para colunas fecharem na impressora:",
  ["proporcional", "monoespaçada (Courier New)", "itálica", "decorativa"],
  1, "Largura fixa por caractere."),
],
20: [
 ("Os itens do cupom do nosso sistema vêm:",
  ["texto fixo no código", "do banco via Recordset", "de um .bmp", "do Clipboard"],
  1, "Saída de dados: SQL alimenta o layout."),
 ("Um documento fiscal identifica:",
  ["só o total", "emitente, numeração, data, itens e totais", "só o cliente", "o programador"],
  1, "Blocos obrigatórios mesmo no modelo didático."),
 ("Totais e valores no cupom usam:",
  ["Str sem formato", "Format(v, \"0.00\")", "Val", "Len"],
  1, "Aparência profissional e conferência fácil."),
],
21: [
 ("O Package & Deployment Wizard gera:",
  ["o banco", "o pacote de instalação (setup + dependentes)", "o relatório", "o backup"],
  1, "Empacota exe, runtimes, dados e atalhos."),
 ("Senha/servidor de conexão ficam em:",
  ["compilados no exe", "config.ini lido em execução", "título do form", "Registry"],
  1, "Mesmo pacote serve a ambientes diferentes."),
 ("O teste de instalação acontece em:",
  ["máquina do desenvolvedor", "máquina/conta limpa", "qualquer uma", "só no papel"],
  1, "Revela dependência esquecida no pacote."),
],
22: [
 ("No VB6, os recursos gráficos da ementa (herança DOS) vivem no:",
  ["Printer", "PictureBox", "ListBox", "Timer"],
  1, "Line/Circle/PSet com coordenadas e cores."),
 ("Retângulo PREENCHIDO no PictureBox:",
  ["Line com B", "Line com BF", "Circle BF", "PSet B"],
  1, "B = borda; BF = box filled."),
 ("PSet desenha:",
  ["um ponto", "um círculo", "uma linha", "um texto"],
  0, "Ondas e texturas nascem de laços com PSet."),
],
23: [
 ("O checklist de integração do projeto cobra:",
  ["só telas", "banco+CRUD+módulos+arquivos+relatório+pacote", "só relatório", "só backup"],
  1, "Todas as camadas do semestre juntas."),
 ("Congelar escopo na semana 23 é:",
  ["não testar", "não adicionar funções novas; pendências viram 'versão 2'", "parar de programar", "adiar a prova"],
  1, "Entrega e apresentação confiáveis."),
 ("Funções de regra no projeto ficam em:",
  ["dentro dos botões", "Modules (.bas) reutilizáveis", "no banco", "no instalador"],
  1, "Formulário orquestra; módulos sabem fazer."),
],
24: [
 ("Na demonstração, barrar uma entrada inválida ao vivo prova:",
  ["bug", "que a validação funciona", "lentidão", "falta de teste"],
  1, "Erro tratado é qualidade demonstrada."),
 ("A prova final escrita (30 pts) é:",
  ["em duplas com consulta", "individual e cumulativa", "oral", "só projeto"],
  1, "Conforme o Plano de Ensino; +10 pts do projeto."),
 ("O pacote entregue inclui:",
  ["só o exe", "exe+dependentes+config.ini+atalhos", "banco com senhas", "fontes crus"],
  1, "Distribuição profissional e configurável."),
],
}

TITULOS_AULAS = {
    1: "Ambientação e primeiro programa VB6", 2: "SGBD — instalação e configuração",
    3: "SGBD — conexão", 4: "SQL — fundamentos", 5: "SQL — manipulação",
    6: "SQL — consultas e filtros", 7: "Programação estruturada", 8: "Vetores",
    9: "Matrizes", 10: "Registros", 11: "Strings", 12: "Modularização",
    13: "Arquivos e textos", 14: "Arquivos + dados", 15: "Cliente/Servidor (ADO)",
    16: "Cliente/Servidor — prática", 17: "Backup", 18: "Recuperação",
    19: "Relatórios", 20: "Documentos fiscais", 21: "Disco de instalação",
    22: "Recursos gráficos", 23: "Integração do projeto", 24: "Consolidação e avaliação final",
}

ALIASES = {}
