# -*- coding: utf-8 -*-
"""Quiz básico por AULA — 3 questões por aula (72 aulas).
Formato: (enunciado, [4 alternativas], índice da correta, explicação curta)
"""

Q = {
1: [
 ("O que é uma rede de computadores?",
  ["Conjunto de dispositivos conectados que trocam informações", "Um único computador com muitos arquivos", "Um site de relacionamento entre computadores", "Um programa de editar textos"],
  0, "Rede = dispositivos interligados para trocar dados; a Internet é uma rede mundial de redes."),
 ("Na Web, qual é o papel do navegador (Chrome, Firefox...)?",
  ["Servidor, pois guarda os sites", "Cliente, pois solicita páginas ao servidor", "DNS, pois traduz endereços", "Protocolo, pois define as regras"],
  1, "O navegador é o software cliente: requisita e exibe a resposta do servidor."),
 ("Qual frase está correta?",
  ["Internet e Web são a mesma coisa", "A Web é um dos serviços que funcionam sobre a Internet", "A Internet é um site gigante", "A Web existe sem a Internet"],
  1, "Internet = infraestrutura; Web = serviço de páginas (como e-mail e streaming são outros serviços)."),
],
2: [
 ("Qual é a ordem do ciclo da Web?",
  ["Resposta → requisição → processamento", "Requisição do navegador → processamento no servidor → resposta", "Processamento no navegador → resposta do servidor", "DNS → resposta → requisição"],
  1, "O navegador pede (requisição), o servidor processa e devolve (resposta) o HTML."),
 ("Em comparação com o HTTP, o HTTPS adiciona:",
  ["Criptografia na comunicação", "Mais cores às páginas", "Hospedagem gratuita", "Registro de domínio automático"],
  0, "HTTPS = HTTP + criptografia; o cadeado indica conexão segura."),
 ("Na URL https://escola.edu.br/ava/login.php, qual é o DOMÍNIO?",
  ["https", "escola.edu.br", "/ava/", "login.php"],
  1, "Domínio é o nome do site; /ava/ é caminho e login.php é o recurso."),
],
3: [
 ("A função do DNS é:",
  ["Hospedar os arquivos do site", "Traduzir o nome do domínio em endereço IP", "Criptografar senhas", "Exibir as páginas no navegador"],
  1, "DNS é a 'agenda' da Internet: nome → IP."),
 ("O endereço IP identifica:",
  ["O formato dos arquivos", "Um dispositivo na rede, por meio de um número", "A cor do site", "A pasta do projeto"],
  1, "IP é o 'número da casa' do dispositivo na rede."),
 ("Para deixar um site no ar 24h por dia, contratamos:",
  ["Um editor de código", "Um navegador pago", "Uma hospedagem", "Um teclado melhor"],
  2, "Hospedagem = espaço em servidor ligado continuamente, com servidor Web."),
],
4: [
 ("e-Commerce é:",
  ["A compra e venda on-line (loja virtual)", "O conjunto de processos internos da empresa", "Um portal de notícias", "Um protocolo de rede"],
  0, "e-commerce = vendas on-line; faz parte do e-business."),
 ("Qual relação está correta?",
  ["e-business e e-commerce são sinônimos", "Todo e-commerce faz parte de um e-business", "e-business é só vendas", "e-commerce é maior que e-business"],
  1, "e-business é o conceito amplo (negócio digital); e-commerce é a parte de vendas."),
 ("Ordem correta do fluxo de uma loja virtual:",
  ["Checkout → carrinho → catálogo → início", "Início → catálogo → ficha do produto → carrinho → checkout", "Carrinho → início → checkout → catálogo", "Catálogo → checkout → carrinho → início"],
  1, "Fluxo clássico: início → catálogo → ficha → carrinho → checkout → confirmação."),
],
5: [
 ("Qual ferramenta é a adequada para ESCREVER os arquivos do site?",
  ["Microsoft Word", "Editor de código (VS Code)", "Excel", "PowerPoint"],
  1, "Código é texto puro: editor de código, nunca processadores de texto."),
 ("A página inicial de um site deve se chamar:",
  ["inicio2.html", "home-page.doc", "index.html", "principal.txt"],
  2, "O servidor procura automaticamente index.html/index.php ao acessar o site."),
 ("No terminal, qual comando CRIA uma pasta?",
  ["cd", "dir", "del", "mkdir"],
  3, "mkdir = make directory (criar pasta); cd navega, dir lista."),
],
6: [
 ("HTML é uma linguagem de:",
  ["Programação, com variáveis e decisões", "Marcação, que estrutura o conteúdo", "Banco de dados", "Sistema operacional"],
  1, "HTML marca o conteúdo (título, parágrafo...); quem programa é o PHP."),
 ("O conteúdo VISÍVEL da página fica dentro de:",
  ["<head>", "<title>", "<body>", "<meta>"],
  2, "body = corpo visível; head = configurações e metadados."),
 ("O texto que aparece na ABA do navegador é definido por:",
  ["<h1>", "<title>", "<p>", "<body>"],
  1, "title (dentro do head) define o título da aba; h1 é o título na página."),
],
7: [
 ("Um elemento HTML é formado por:",
  ["Somente texto", "Tag de abertura + conteúdo + tag de fechamento", "Apenas atributos", "Um comentário e uma imagem"],
  1, "Ex.: <p>texto</p> — abertura, conteúdo, fechamento."),
 ("Qual elemento NÃO tem tag de fechamento?",
  ["<p>", "<h1>", "<br>", "<strong>"],
  2, "br, hr, img, meta e input são elementos vazios."),
 ("Os atributos de um elemento são escritos:",
  ["Na tag de abertura, como nome=\"valor\"", "Dentro do fechamento", "Fora do elemento", "Sempre no <head>"],
  0, "Atributos ficam na tag de abertura: <html lang=\"pt-br\">."),
],
8: [
 ("Qual tag representa o título PRINCIPAL da página?",
  ["<h6>", "<p>", "<title>", "<h1>"],
  3, "h1 é o título principal (idealmente único por página)."),
 ("Para quebrar uma linha DENTRO do mesmo parágrafo usamos:",
  ["<hr>", "<br>", "<p>", "<h2>"],
  1, "br = quebra de linha; hr = separador horizontal."),
 ("Qual elemento marca uma mudança de assunto com uma linha horizontal?",
  ["<br>", "<hr>", "<em>", "<li>"],
  1, "hr desenha um separador horizontal entre blocos."),
],
9: [
 ("Qual tag indica que o texto é IMPORTANTE (semântica)?",
  ["<b>", "<font>", "<strong>", "<span>"],
  2, "strong transmite importância; b é apenas aparência."),
 ("A tag <mark> serve para:",
  ["Destacar/marcar um trecho", "Apagar texto", "Deixar em subscrito", "Criar um link"],
  0, "mark exibe o texto destacado (fundo amarelo por padrão)."),
 ("Por que preferir <strong> a <b>?",
  ["Carrega mais rápido", "Muda a cor do texto", "Transmite significado a leitores de tela e buscadores", "É obrigatório pelo navegador"],
  2, "Semântica ajuda acessibilidade (leitores de tela) e SEO."),
],
10: [
 ("Um link é criado com qual tag e atributo?",
  ["<img src>", "<a href>", "<p link>", "<table href>"],
  1, "<a href=\"destino\">texto</a>."),
 ("Links INTERNOS (entre páginas do mesmo site) usam:",
  ["URL absoluta com https://", "Caminho relativo (ex.: sobre.html)", "O endereço IP do servidor", "O nome do provedor"],
  1, "Interno = caminho relativo; externo = URL absoluta."),
 ("Para abrir o link em NOVA ABA usamos:",
  ["target=\"_blank\"", "href=\"_new\"", "rel=\"tab\"", "open=\"sim\""],
  0, "target=\"_blank\" abre em nova aba/janela."),
],
11: [
 ("Qual elemento exibe uma imagem?",
  ["<image link>", "<a src>", "<img src alt>", "<foto>"],
  2, "<img> é elemento vazio com src (arquivo) e alt (descrição)."),
 ("O atributo alt serve para:",
  ["Definir o tamanho da imagem", "Descrever a imagem (acessibilidade e falha de carregamento)", "Escolher o formato do arquivo", "Criar uma pasta de imagens"],
  1, "alt é lido por leitores de tela e aparece se a imagem não carregar."),
 ("Qual formato é o mais indicado para imagens com FUNDO TRANSPARENTE?",
  ["JPEG", "PNG", "GIF de fotos", "BMP pesado"],
  1, "PNG suporta transparência; JPEG é para fotos."),
],
12: [
 ("Lista NÃO ordenada (a ordem não importa) usa:",
  ["<ol> e <li>", "<ul> e <li>", "<dl> e <dt>", "<table> e <tr>"],
  1, "ul = unordered list, com marcadores."),
 ("Para passos de uma receita (ordem importa), usamos:",
  ["<ul>", "<dl>", "<ol>", "<li> solto"],
  2, "ol numera os itens automaticamente."),
 ("A lista de DEFINIÇÃO (termo + significado) usa:",
  ["<dl>, <dt> e <dd>", "<ul> e <ol>", "<h1> e <p>", "<dt> e <ul>"],
  0, "dl = definition list; dt = termo; dd = definição."),
],
13: [
 ("Em uma tabela, cada LINHA é criada com:",
  ["<td>", "<tr>", "<th>", "<table>"],
  1, "tr = table row (linha)."),
 ("A célula de CABEÇALHO (título de coluna) é:",
  ["<td>", "<caption>", "<th>", "<tr>"],
  2, "th destaca (negrito/centrado por padrão)."),
 ("Toda célula (<td> ou <th>) precisa estar dentro de:",
  ["<table> diretamente", "<thead> apenas", "<tr>", "<tbody> apenas"],
  2, "A ordem é sempre table → tr → th/td."),
],
14: [
 ("O atributo colspan=\"2\" faz a célula:",
  ["Ocupar 2 linhas", "Ocupar 2 colunas", "Criar 2 tabelas", "Ter borda dupla"],
  1, "colspan mescla colunas; rowspan mescla linhas."),
 ("As seções cabeçalho, corpo e rodapé da tabela são:",
  ["head, body, foot", "thead, tbody, tfoot", "top, mid, bottom", "th, td, tr"],
  1, "thead/tbody/tfoot organizam semanticamente a tabela."),
 ("Numa tabela de 3 colunas, uma linha com uma célula colspan=\"2\" deve ter, ao todo, quantas células?",
  ["3 células normais", "2 células (a de colspan conta por 2)", "4 células", "1 célula"],
  1, "Some: colspan 2 + 1 célula = 3 colunas. Células 'engolidas' são removidas."),
],
15: [
 ("Qual atributo do campo é usado pelo PHP para ler o valor enviado?",
  ["id", "class", "name", "for"],
  2, "name é a chave em $_POST/$_GET; id serve para label/CSS."),
 ("Para MÚLTIPLAS escolhas independentes (hobbies), usamos:",
  ["radio com mesmo name", "checkbox", "input date", "select obrigatório"],
  1, "checkbox marca/desmarca opções independentes."),
 ("O <label for=\"x\"> deve casar com qual atributo do input?",
  ["name=\"x\"", "id=\"x\"", "value=\"x\"", "type=\"x\""],
  1, "for aponta para o id do campo (clicar no label foca o campo)."),
],
16: [
 ("Para campo de SENHA (caracteres ocultos), o type é:",
  ["text", "secret", "password", "mask"],
  2, "type=\"password\" oculta os caracteres digitados."),
 ("Qual atributo torna o preenchimento OBRIGATÓRIO?",
  ["mandatory", "required", "notnull", "obrigatorio"],
  1, "required bloqueia o envio vazio (mas pode ser contornado: valide no servidor!)."),
 ("O atributo placeholder exibe:",
  ["Uma dica dentro do campo, em cinza", "O título da aba", "O valor final do campo", "Um erro permanente"],
  0, "placeholder é exemplo/dica; não substitui o label."),
],
17: [
 ("A lista SUSPENSA (menu de opções) é criada com:",
  ["<ul> e <li>", "<select> e <option>", "<input list>", "<menu-drop>"],
  1, "select + option; value define o valor enviado."),
 ("Para mensagem de VÁRIAS LINHAS usamos:",
  ["<input type=\"text\">", "<p>", "<textarea>", "<pre auto>"],
  2, "textarea tem abertura e fechamento e aceita rows/cols."),
 ("O botão que ENVIA o formulário tem:",
  ["type=\"submit\"", "type=\"send\"", "type=\"go\"", "action=\"sim\""],
  0, "button type=\"submit\" envia; type=\"reset\" limpa."),
],
18: [
 ("O projeto A1 'site da empresa fictícia' tem quantas páginas?",
  ["1", "2", "4", "7"],
  2, "index, empresa, produtos e contato, com menu em todas."),
 ("Na página PRODUTOS do projeto, o conteúdo principal é:",
  ["Um formulário de login", "Uma tabela com thead/tbody/tfoot e colspan", "Um vídeo", "Uma lista de links externos"],
  1, "A tabela de produtos demonstra domínio de tabelas."),
 ("Na página CONTATO, o elemento principal é:",
  ["Uma tabela", "Um formulário completo (select, textarea, checkbox)", "Uma galeria de imagens", "Um cabeçalho h6"],
  1, "Formulário com nome, e-mail, assunto (select), mensagem (textarea) e checkbox."),
],
19: [
 ("O código PHP é executado:",
  ["No navegador do usuário", "No servidor Web", "No editor de código", "No DNS"],
  1, "PHP é server-side: o servidor executa e envia HTML pronto."),
 ("Ao acessar uma página .php, o navegador recebe:",
  ["O código PHP colorido", "Somente o HTML gerado", "O banco de dados", "Arquivos .php crus"],
  1, "Ctrl+U mostra só HTML: o PHP nunca chega ao cliente."),
 ("Qual pacote instala servidor Web + PHP para estudo local?",
  ["XAMPP", "VS Code", "Google Chrome", "Git"],
  0, "XAMPP (Apache + PHP + MySQL); projeto vai em htdocs/ e acessa via localhost."),
],
20: [
 ("Um bloco de código PHP abre e fecha com:",
  ["<php> ... </php>", "<?php ... ?>", "{php ... }", "<!-- php -->"],
  1, "Blocos: <?php abre e ?> fecha."),
 ("Qual comando envia conteúdo para a página?",
  ["show", "write", "echo", "display"],
  2, "echo \"texto\"; envia a saída para a resposta."),
 ("Toda instrução PHP termina com:",
  ["Ponto final", "Vírgula", "Dois-pontos", "Ponto e vírgula"],
  3, "Esquecer o ; é o erro nº 1 de iniciante (Parse error)."),
],
21: [
 ("Em um arquivo .php, HTML e PHP:",
  ["Não podem coexistir", "Podem ser misturados no mesmo arquivo", "O HTML é apagado ao salvar", "O PHP vira comentário"],
  1, "O servidor executa os blocos PHP e entrega um HTML único."),
 ("'Conteúdo dinâmico' significa que:",
  ["A página muda a cada execução (ex.: data/hora)", "A página é sempre idêntica", "Só imagens mudam", "O CSS anima sozinho"],
  0, "O mesmo arquivo gera resultados diferentes a cada acesso."),
 ("Em PHP, o operador que CONCATENA textos é:",
  ["+", ".", ",", "&"],
  1, "O ponto junta strings: \"Olá, \" . $nome."),
],
22: [
 ("Toda variável PHP começa com:",
  ["#", "@", "$", "&"],
  2, "Ex.: $nome = \"Maria\";"),
 ("Qual nome de variável é VÁLIDO?",
  ["$2preco", "$preco final", "$precoFinal", "preco$"],
  2, "Começa com $ + letra/underscore; sem números no início, acentos ou espaços."),
 ("Uma CONSTANTE em PHP é definida com:",
  ["define(\"PI\", 3.14)", "$PI = fix", "constante PI()", "pi_var = 3.14"],
  0, "define() cria constante (sem $, em MAIÚSCULAS por convenção)."),
],
23: [
 ("A função var_dump() exibe:",
  ["Somente o valor", "Somente o tipo", "O tipo E o valor da variável", "Os erros do arquivo"],
  2, "var_dump é a 'lupa' do programador para tipos e valores."),
 ("O valor 1.65 é do tipo:",
  ["integer", "float", "string", "boolean"],
  1, "Números com casas decimais são float (double)."),
 ("O valor \"17\" (entre aspas) é do tipo:",
  ["integer", "float", "string", "boolean"],
  2, "Entre aspas é texto, mesmo parecendo número."),
],
24: [
 ("Quanto vale 10 % 3 em PHP?",
  ["3", "3.33", "1", "0"],
  2, "% é o RESTO da divisão inteira: 10 ÷ 3 = 3, resto 1."),
 ("Quanto vale 7 / 2 em PHP?",
  ["3", "3.5", "1", "35"],
  1, "A divisão / produz resultado decimal quando necessário."),
 ("Para juntar \"7\" com \"2\" como TEXTO (\"72\") usamos:",
  ["+", ".", "*", "%"],
  1, "O ponto concatena; o + somaria números."),
],
25: [
 ("O resultado de 5 === \"5\" é:",
  ["true", "false", "erro de sintaxe", "\"5\""],
  1, "=== compara valor E tipo: integer ≠ string."),
 ("O operador == compara:",
  ["Valor e tipo ao mesmo tempo", "Apenas o valor (convertendo tipos)", "Apenas o tipo", "Nada, é decorativo"],
  1, "== é 'frouxo': \"5\" vira 5 na comparação."),
 ("\"Ana\" == \"ana\" resulta em:",
  ["true", "false", "erro", "null"],
  1, "Comparações de texto diferenciam maiúsculas de minúsculas."),
],
26: [
 ("Quanto vale true && false?",
  ["true", "false", "null", "erro"],
  1, "&& (E) só é true se OS DOIS lados forem true."),
 ("Quanto vale true || false?",
  ["false", "null", "true", "erro"],
  2, "|| (OU) é true se pelo menos um lado for true."),
 ("Quanto vale !true?",
  ["true", "false", "1", "null"],
  1, "! (NÃO) inverte o valor lógico."),
],
27: [
 ("O bloco de um if é executado quando:",
  ["Sempre", "A condição é verdadeira (true)", "A condição é falsa", "Existe um else"],
  1, "if executa somente com condição true."),
 ("Dentro do if, é um ERRO clássico usar:",
  ["== para comparar", "= (atribuição) no lugar de == ou ===", "chaves { }", "comparações"],
  1, "= atribui e quase sempre torna a condição 'verdadeira' sem comparar."),
 ("As chaves { } no if servem para:",
  ["Delimitar o bloco de comandos", "Comentar o código", "Encerrar o PHP", "Criar variáveis"],
  0, "Com ou sem chaves para 1 comando, o curso adota SEMPRE chaves."),
],
28: [
 ("Com $nota = 6.5 e a cadeia (>=7 aprovado; >=5 recuperação; else reprovado), a saída é:",
  ["APROVADO", "RECUPERAÇÃO", "REPROVADO", "ERRO"],
  1, "6.5 não é >= 7, mas é >= 5 → RECUPERAÇÃO."),
 ("Em uma cadeia if/elseif/else, quantos blocos executam?",
  ["Todos os verdadeiros", "Apenas o primeiro verdadeiro", "Sempre dois", "Todos"],
  1, "Só o primeiro bloco cuja condição é true; o resto é ignorado."),
 ("A ordem recomendada das condições é:",
  ["Da mais restritiva para a menos restritiva", "Qualquer ordem", "Da menos restritiva primeiro", "Alfabética"],
  0, "Testar >= 7 antes de >= 5 evita classificações erradas."),
],
29: [
 ("A estrutura switch é ideal para:",
  ["Comparar uma variável com valores fixos (menus)", "Faixas de valores (>=, <=)", "Repetir tarefas", "Definir funções"],
  0, "switch compara um valor com cases fixos."),
 ("Se esquecermos o break em um case:",
  ["O programa para", "Ocorre cascata: os cases seguintes também executam", "Vira um laço infinito", "O default é ignorado"],
  1, "Sem break, a execução 'vaza' para os próximos cases."),
 ("O 'else' do switch chama-se:",
  ["case 0", "end", "default", "otherwise"],
  2, "default executa quando nenhum case bate."),
],
30: [
 ("Quantas voltas executa for ($i = 1; $i <= 5; $i++)?",
  ["4", "5", "6", "Infinitas"],
  1, "$i = 1,2,3,4,5 → 5 voltas."),
 ("O incremento $i++ equivale a:",
  ["$i = $i + 1", "$i = 1", "$i == 1", "$i = $i - 1"],
  0, "$i++ soma 1 ao contador a cada volta."),
 ("Usamos for quando:",
  ["Sabemos quantas vezes repetir", "Nunca sabemos nada", "Só com arrays associativos", "A condição é secreta"],
  0, "for = repetição com contador conhecido."),
],
31: [
 ("O while testa a condição:",
  ["Depois de executar o bloco", "Antes de executar o bloco", "Nunca testa", "No fim da página"],
  1, "while = 'enquanto': verifica antes de cada volta."),
 ("Um LAÇO INFINITO com while geralmente acontece quando:",
  ["A variável de controle não avança", "Usamos $i++", "A condição vira false", "Usamos chaves"],
  0, "Sem o passo que caminha para o fim, a condição nunca vira false."),
 ("Se a condição já é false no início, o while executa:",
  ["1 vez", "0 vezes", "10 vezes", "Infinito"],
  1, "Teste antes: condição falsa de início = nenhuma execução."),
],
32: [
 ("O do...while executa o bloco, no mínimo:",
  ["0 vezes", "1 vez", "2 vezes", "5 vezes"],
  1, "Ele faz primeiro e testa depois."),
 ("A diferença do do...while para o while é:",
  ["O teste da condição acontece DEPOIS do bloco", "O teste acontece antes", "Não há condição", "Só funciona com arrays"],
  0, "do...while garante ao menos uma execução."),
 ("Depois do while (cond) final do do...while, é obrigatório usar:",
  ["Vírgula", "Ponto e vírgula", "Chaves", "Nada"],
  1, "Sintaxe: do { } while (cond); — com ; no fim."),
],
33: [
 ("O índice do PRIMEIRO elemento de um array é:",
  ["1", "0", "-1", "\"um\""],
  1, "Arrays indexados começam em [0]."),
 ("Para saber QUANTOS elementos um array tem, usamos:",
  ["size()", "len()", "count()", "total()"],
  2, "count($array) devolve a quantidade de elementos."),
 ("Para ADICIONAR um item no FINAL do array usamos:",
  ["$arr[] = $valor", "$arr + $valor", "add($arr, $valor)", "$arr[0] = $valor"],
  0, "Colchetes vazios acrescentam ao final."),
],
34: [
 ("O laço foreach serve para:",
  ["Percorrer todos os elementos de um array", "Contar até 10", "Definir funções", "Criar tabelas HTML"],
  0, "foreach ($array as $item) percorre item a item."),
 ("Em foreach ($a as $k => $v):",
  ["$k é a chave e $v é o valor", "$k é o valor e $v a chave", "$k é o total", "$v é o índice do foreach"],
  0, "A versão com => traz chave e valor juntos."),
 ("O foreach precisa de contador manual ($i++)?",
  ["Sim, sempre", "Não — ele avança sozinho", "Só em arrays indexados", "Só em associativos"],
  1, "O foreach controla o percurso automaticamente."),
],
35: [
 ("Um array ASSOCIATIVO usa:",
  ["Somente índices numéricos", "Chaves com nome (ex.: \"nome\", \"idade\")", "Somente valores booleanos", "Nenhuma chave"],
  1, "Pares chave => valor com chaves significativas."),
 ("Como acessar o nome em $aluno = [\"nome\" => \"Ana\"]?",
  ["$aluno[0]", "$aluno[\"nome\"]", "$aluno(nome)", "$aluno.nome"],
  1, "Acesso pela chave: $aluno[\"nome\"]."),
 ("Qual sintaxe cria um par chave-valor?",
  ["\"nome\" = \"Ana\"", "\"nome\" : \"Ana\"", "\"nome\" => \"Ana\"", "\"nome\" -> \"Ana\""],
  2, "A seta => liga chave ao valor."),
],
36: [
 ("A abreviação <?= $x ?> equivale a:",
  ["<?php echo $x; ?>", "<?php $x ?>", "<!-- $x -->", "echo sem PHP"],
  0, "<?= ?> é atalho de echo dentro do HTML."),
 ("A sintaxe alternativa do foreach termina com:",
  ["endfor", "endforeach;", "foreach_end", "} apenas"],
  1, "foreach (...): ... endforeach; — legível em templates."),
 ("No projeto 'cadastro simples', a lista de alunos foi exibida em:",
  ["Uma tabela HTML gerada pelo PHP", "Um PDF automático", "Uma imagem PNG", "Um e-mail"],
  0, "foreach gerando <tr>/<td> dentro de <table>."),
],
37: [
 ("Com method=\"get\", os dados do formulário viajam:",
  ["No corpo da requisição", "Visíveis na URL, após o ?", "Em um cookie", "Somente no histórico"],
  1, "GET: nome=valor aparece na barra de endereços."),
 ("No PHP, os dados GET são lidos em:",
  ["$_GET[\"campo\"]", "$GET(campo)", "$_POST[\"campo\"]", "$_URL[\"campo\"]"],
  0, "$_GET é um array associativo automático (chave = name do campo)."),
 ("GET é adequado para:",
  ["Enviar senhas", "Buscas e filtros (dados públicos)", "Dados de cartão", "Cadastros pessoais"],
  1, "GET para consultar; dados sensíveis sempre POST."),
],
38: [
 ("Com method=\"post\", os dados viajam:",
  ["Na URL", "No corpo da requisição (invisíveis na barra)", "No título da página", "No DNS"],
  1, "POST mantém a URL limpa."),
 ("Para um formulário de LOGIN com senha, o método indicado é:",
  ["GET", "POST", "Tanto faz", "FTP"],
  1, "Senha nunca na URL: POST."),
 ("$_POST é:",
  ["Uma função", "Uma constante", "Um array associativo automático", "Uma string"],
  2, "Chaves = name dos campos; valores = o que foi digitado."),
],
39: [
 ("A função isset() verifica se o dado:",
  ["Está vazio", "Foi enviado (existe)", "É numérico", "Está criptografado"],
  1, "isset = 'veio?'; empty = 'veio vazio?'."),
 ("empty(\"\") retorna:",
  ["true", "false", "null", "erro"],
  0, "String vazia é considerada vazia (true)."),
 ("Confiar apenas no required do HTML é seguro?",
  ["Sim, é suficiente", "Não: é obrigatório validar no servidor", "Sim, em qualquer navegador", "Depende da cor do site"],
  1, "O required pode ser contornado; a validação séria é no PHP."),
],
40: [
 ("htmlspecialchars() protege principalmente contra:",
  ["Ataques XSS (script injetado)", "Internet lenta", "Erro 404", "Laços infinitos"],
  0, "Converte < > & aspas em entidades: dado vira texto, não código."),
 ("A função converte o caractere < em:",
  ["&gt;", "&lt;", "&amp;", "<br>"],
  1, "< vira &lt; e > vira &gt;."),
 ("Quando aplicar htmlspecialchars?",
  ["Ao EXIBIR dados vindos do usuário", "Ao criar pastas", "No CSS", "Somente em URLs"],
  0, "Sanitização de saída: todo dado do usuário exibido passa por ela."),
],
41: [
 ("Qual é o fluxo correto de um formulário com PHP?",
  ["Processar → preencher → resultado", "Preencher → enviar → processar (validar) → resultado", "Resultado → enviar → preencher", "Enviar → preencher → processar"],
  1, "HTML preenche, POST envia, PHP valida/processa, página confirma."),
 ("Ao encontrar vários campos com erro, a boa prática é:",
  ["Mostrar todos os erros de uma vez", "Mostrar só o primeiro e apagar o resto", "Ignorar os erros", "Recarregar sem mensagem"],
  0, "Array $erros[]: valida tudo e exibe tudo junto."),
 ("No processamento, o comando exit serve para:",
  ["Interromper a execução em caso de erro", "Acelerar a página", "Apagar os dados", "Fechar o navegador"],
  0, "Com erros, exibe as mensagens e para (não processa)."),
],
42: [
 ("O projeto 'cadastro de alunos' do módulo usa quais arquivos?",
  ["cadastro.html + processar.php", "Somente index.html", "Somente .pdf", "listar.doc + nota.txt"],
  0, "Formulário HTML + processamento PHP."),
 ("Para validar idade entre 10 e 120 usamos:",
  ["Comparações < e > (ou <= >=)", "strlen()", "htmlspecialchars()", "count()"],
  0, "Regra de faixa: if ($idade < 10 || $idade > 120) erro."),
 ("O link 'Voltar' na página de erro serve para:",
  ["O usuário corrigir os dados no formulário", "Apagar o formulário", "Enviar e-mail", "Formatar o CSS"],
  0, "Erro claro + caminho de volta = boa usabilidade."),
],
43: [
 ("As partes reutilizáveis (cabecalho, rodape) ficam na pasta:",
  ["imagens/", "css/", "includes/", "lixeira/"],
  2, "includes/ centraliza o que é reutilizado."),
 ("Organizar os arquivos do projeto ajuda principalmente em:",
  ["Manutenção e trabalho em equipe", "Velocidade da internet", "Criptografia", "Cor das fontes"],
  0, "Encontrar rápido, reutilizar, hospedar e colaborar."),
 ("Nomes de arquivos devem ser:",
  ["Minúsculos, sem acentos e sem espaços", "Maiúsculos com acentos", "Com espaços longos", "Aleatórios"],
  0, "Padrão evita links quebrados em servidores."),
],
44: [
 ("O comando include serve para:",
  ["Inserir o conteúdo de outro arquivo na página", "Criar tabelas", "Estilizar texto", "Consultar bancos"],
  0, "Reutilização: escrever 1×, incluir N×."),
 ("Se o arquivo NÃO existir, o require:",
  ["Emite aviso e continua", "Gera erro fatal e para a página", "Ignora silenciosamente", "Cria o arquivo"],
  1, "require = essencial; include = opcional (warning)."),
 ("Mudar o menu uma única vez e atualizar todas as páginas é possível com:",
  ["include do cabecalho.php", "copiar e colar em 10 arquivos", "CSS apenas", "DNS"],
  0, "Cabeçalho centralizado = manutenção em um lugar só."),
],
45: [
 ("Uma função devolve seu resultado com:",
  ["echo", "print", "return", "exit"],
  2, "return devolve o valor (e encerra a função)."),
 ("Um PARÂMETRO de função é:",
  ["Um valor de ENTRADA definido na função", "O valor de saída", "Uma variável global", "Um comentário"],
  0, "Parâmetro entra; return sai."),
 ("Uma função SEM return devolve:",
  ["0", "false", "null", "erro fatal"],
  2, "Sem return, o resultado é null."),
],
46: [
 ("A função calcularMedia($n1, $n2) deve retornar:",
  ["($n1 + $n2) / 2", "$n1 + $n2", "2", "echo da soma"],
  0, "Média = soma das notas dividida por 2, via return."),
 ("Funções que retornam true/false são perfeitas para:",
  ["Usar em condições de if", "Imprimir tabelas", "Criar pastas", "Definir cores"],
  0, "if (verificarMaioridade($idade)) { ... }."),
 ("A expressão cond ? \"Sim\" : \"Não\" é:",
  ["Um if/else de uma linha (ternário)", "Um laço", "Uma função", "Um array"],
  0, "Operador ternário: condição ? valor se true : valor se false."),
],
47: [
 ("Em $alunos[0][\"nome\"], acessamos:",
  ["O campo nome do primeiro aluno da lista", "O aluno de número 'nome'", "Um erro garantido", "O total de alunos"],
  0, "Dois colchetes: posição na lista + campo da ficha."),
 ("Um array MULTIDIMENSIONAL é:",
  ["Um array cujos elementos também são arrays", "Um array com exatamente 2 valores", "Um array de funções", "Um array sem chaves"],
  0, "Lista de fichas: linhas × colunas, como uma tabela."),
 ("Para percorrer as duas dimensões usamos:",
  ["foreach aninhado (um dentro do outro)", "Um único for", "switch", "include"],
  0, "1º foreach: cada aluno; 2º: cada campo da ficha."),
],
48: [
 ("Na listagem dinâmica, as tags <tr>/<td> são escritas:",
  ["Uma única vez, dentro do foreach", "Uma vez por aluno, manualmente", "No CSS", "No JavaScript"],
  0, "O foreach repete o bloco para cada registro."),
 ("Com 300 alunos cadastrados, o código da listagem:",
  ["Permanece o mesmo — só o array muda", "Cresce 300 vezes", "Precisa de 300 arquivos", "Quebra"],
  0, "Geração dinâmica: código fixo, dados variáveis."),
 ("A Avaliação 2 (A2) é aplicada em:",
  ["Semana 1", "Semana 8", "Semana 16 (aula 48)", "Semana 24"],
  2, "Prova de HTML + PHP + GET/POST na semana 16."),
],
49: [
 ("O projeto final integrador é desenvolvido:",
  ["Individualmente, em prova", "Em grupos, como aplicação Web", "Em dupla apenas no papel", "Somente apresentação"],
  1, "Aplicação Web funcional em grupos (3–4 alunos)."),
 ("Qual destes é um tema sugerido para o projeto?",
  ["Jogo 3D com realidade virtual", "Controle de tarefas / biblioteca / cadastro de alunos", "Rede social global", "Mineração de criptomoedas"],
  1, "Temas simples e reais: alunos, contatos, produtos, clientes, biblioteca, tarefas."),
 ("A melhor escolha de tema é:",
  ["O mais ambicioso, mesmo pela metade", "Um que o grupo entenda e consiga COMPLETAR", "Um copiado da internet", "Nenhum tema"],
  1, "Simples e completo vale mais que ambicioso e inacabado."),
],
50: [
 ("As 5 perguntas do levantamento de requisitos são:",
  ["Objetivo, usuários, funcionalidades, páginas e dados", "Cores, fontes, logos, banners e vídeos", "Preço, lucro, imposto, venda e compra", "CPU, RAM, disco, rede e fonte"],
  0, "Planejar antes de codificar evita retrabalho."),
 ("Um BOM requisito deve ser:",
  ["'O sistema deve ser bonito'", "Concreto e testável (dá para verificar sim/não)", "'O mais rápido possível'", "'Moderno e intuitivo'"],
  1, "Requisito testável vira caso de teste depois."),
 ("A Entrega 1 do projeto final é:",
  ["A proposta e os requisitos do projeto", "O código final", "A apresentação", "A tabela de testes"],
  0, "Documento de 1 página: tema, objetivo, usuários, funcionalidades."),
],
51: [
 ("Qual é a ordem de construção recomendada?",
  ["Listagem → CSS → formulário → estrutura", "Estrutura → includes → página inicial → cadastro → processar → listar", "Apresentação → código → testes", "CSS → imagens → PHP → HTML"],
  1, "Do alicerce ao acabamento, testando a cada passo."),
 ("Devemos testar no navegador:",
  ["Só no final de tudo", "A cada passo concluído", "Nunca", "Somente na entrega"],
  1, "Testar cedo evita pilhas de erros difíceis."),
 ("Todos do grupo devem trabalhar com:",
  ["Cópias diferentes e desatualizadas", "A mesma versão dos arquivos (compartilhada)", "Arquivos só no pen-drive de um", "Nomes diferentes para o mesmo arquivo"],
  1, "Versão única compartilhada evita bugs 'fantasma'."),
],
52: [
 ("Todo campo de formulário deve ter, no mínimo:",
  ["label + name (+ id)", "Somente placeholder", "Somente class", "Nenhum rótulo"],
  0, "label associa o rótulo; name identifica no processamento."),
 ("O processar.php deve PRIMEIRO:",
  ["Exibir os dados", "Confirmar o método POST e validar os campos", "Apagar tudo", "Redirecionar sem verificar"],
  1, "Segurança: verificar origem e validar antes de usar."),
 ("Em caso de erro de validação, exibimos:",
  ["Página em branco", "Mensagens claras + link voltar + exit", "Erro 500 sem explicação", "Nada, só recarrega"],
  1, "Feedback completo e caminho de retorno."),
],
55: [
 ("Para mostrar o TOTAL de registros na listagem usamos:",
  ["sum()", "count()", "total()", "len()"],
  1, "count($array) no tfoot, por exemplo."),
 ("O teste cruzado (outro grupo testando o sistema) serve para:",
  ["Encontrar bugs que os donos não veem", "Atrapalhar os colegas", "Atrasar o projeto", "Copiar o projeto"],
  0, "Olhar novo acha falhas novas — prática profissional."),
 ("Na listagem, os dados vindos de cadastro devem ser exibidos com:",
  ["echo puro", "htmlspecialchars()", "print_r()", "var_dump()"],
  1, "Sanitizar toda saída de dados do usuário."),
],
58: [
 ("As colunas de uma tabela de testes são:",
  ["Teste × entrada × resultado esperado", "Data × hora × autor", "Nome × nota × turma", "Cor × tamanho × fonte"],
  0, "Cada linha é um caso de teste documentado."),
 ("Um CASO DE LIMITE (borda) testa:",
  ["Valores exatamente no mínimo/máximo permitidos", "Sempre valores médios", "Somente campos vazios", "Valores aleatórios"],
  0, "Erros se escondem nas bordas (ex.: ano = 1900 e 2026)."),
 ("O resultado esperado de cada teste deve ser escrito:",
  ["Depois de executar", "Antes de executar", "Nunca", "Pelo navegador"],
  1, "Escrever antes evita 'aceitar' qualquer resultado."),
],
59: [
 ("Um 'Parse error' indica erro de:",
  ["Lógica", "Sintaxe", "Execução", "Segurança"],
  1, "Código fora das regras da linguagem (; faltando, aspas abertas...)."),
 ("A mensagem de erro do PHP informa:",
  ["O arquivo e a linha do problema", "A senha do servidor", "O nome do aluno", "A data do acesso"],
  0, "Ler a mensagem completa é o passo 1 da correção."),
 ("O erro de LÓGICA se caracteriza por:",
  ["Mensagem vermelha gigante", "Nenhuma mensagem — o resultado é que está errado", "Travar o computador", "Alerta do navegador"],
  1, "Código válido fazendo a coisa errada: pega-se com tabela de testes."),
],
60: [
 ("A revisão da aula 60 cobre:",
  ["Somente PHP", "Somente HTML", "Toda a ementa (Web, HTML, PHP e formulários)", "Somente o projeto"],
  2, "Revisão cumulativa: preparação para a prova final."),
 ("Um método de revisão ATIVA é:",
  ["Só reler os slides", "Escrever exemplos de código sem consultar", "Assistir vídeos em 2×", "Copiar do colega"],
  1, "O que você não consegue escrever é o que precisa estudar."),
 ("A Avaliação 3 (A3) é composta de:",
  ["Prova final individual (30) + projeto e apresentação (10)", "Uma prova de 100 pts", "Somente o projeto", "Somente frequência"],
  0, "40 pts: 30 da prova escrita final + 10 do projeto/apresentação."),
],
61: [
 ("A 'daily' de 5 minutos do grupo serve para:",
  ["Definir o que foi feito, o que falta e quem faz o quê", "Bater papo", "Dar nota", "Testar o sistema inteiro"],
  0, "Reunião rápida de alinhamento, como em equipes reais."),
 ("A Entrega 5 (semana 23) corresponde a:",
  ["Aos requisitos", "À estrutura de pastas", "À versão TESTADA do sistema", "À apresentação final"],
  2, "Testes executados, falhas corrigidas e retestadas."),
 ("O checklist de 12 itens do projeto serve para:",
  ["Acompanhar o progresso do grupo", "Enfeitar o caderno", "Substituir os testes", "Atrasar a entrega"],
  0, "Cada item marcado = uma parte pronta e verificada."),
],
70: [
 ("Na demonstração final, o grupo deve mostrar:",
  ["Só a página inicial", "Cadastro válido + tentativa inválida + listagem dinâmica", "Somente o código-fonte", "Apenas um vídeo pronto"],
  1, "Provar que funciona E que trata erros."),
 ("Deixar dados de exemplo já cadastrados antes da apresentação evita:",
  ["A listagem aparecer vazia ao vivo", "Gastar internet", "Erros de CSS", "Perguntas da plateia"],
  0, "Demonstração com listagem populada passa profissionalismo."),
 ("A apresentação ideal dura:",
  ["30 minutos, um aluno só", "5 a 8 minutos, com todos participando", "1 minuto cronometrado", "Leitura do código linha a linha"],
  1, "Roteiro: abertura, objetivo, demonstração, dificuldades, encerramento."),
],
}

# Aulas 52-54, 56-57, 62-69 são cobertas pelos blocos acima (52, 55, 61, 70 agrupam
# semanas temáticas). Para completar as 72 aulas, mapeamos aliases:
ALIASES = {
    53: 52, 54: 52,
    56: 55, 57: 55,
    62: 61, 63: 61, 64: 61, 65: 61, 66: 61, 67: 61, 68: 61, 69: 61,
    71: 70, 72: 70,
}

TITULOS_AULAS = {
    1: "O que é a Internet?", 2: "Como a Web funciona?", 3: "Domínio, hospedagem e servidor Web",
    4: "Portais, e-business e e-commerce", 5: "Ambiente de desenvolvimento",
    6: "Primeiro documento HTML", 7: "Estrutura do HTML", 8: "Cabeçalhos e parágrafos",
    9: "Formatação de textos", 10: "Links", 11: "Imagens", 12: "Listas",
    13: "Tabelas", 14: "Tabelas na prática", 15: "Formulários", 16: "Formulários na prática",
    17: "Select, textarea e buttons", 18: "Projeto HTML (empresa fictícia)",
    19: "O que é PHP?", 20: "Primeiro programa PHP", 21: "PHP + HTML",
    22: "Variáveis", 23: "Tipos de dados", 24: "Operadores", 25: "Operadores de comparação",
    26: "Operadores lógicos", 27: "Estrutura IF", 28: "IF / ELSE / ELSEIF", 29: "SWITCH",
    30: "Laço for", 31: "WHILE", 32: "DO WHILE", 33: "Arrays", 34: "Foreach",
    35: "Arrays associativos", 36: "Revisão e projeto PHP", 37: "GET", 38: "POST",
    39: "Validação", 40: "Sanitização e segurança", 41: "Formulário completo",
    42: "Projeto: cadastro de alunos", 43: "Organização de arquivos", 44: "Include",
    45: "Funções", 46: "Funções na prática", 47: "Arrays multidimensionais",
    48: "Projeto: listagem dinâmica", 49: "Definição do projeto", 50: "Requisitos",
    51: "Estrutura do projeto", 52: "Página inicial, cadastro e processamento",
    55: "Listagem, interface e validação", 58: "Tabela de testes", 59: "Correção de erros",
    60: "Revisão geral", 61: "Desenvolvimento guiado (61–69)", 70: "Finalização e apresentação",
}
